/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.api.Message;
import java.util.ServiceLoader;

public class App {

    public static void main(String[] args) {
        for (Message message : ServiceLoader.load(Message.class)) {
            String output = String.format("[%s] %s", message.getClass(), message.message());
            System.out.println(output);
        }
    }
}
